class Scheduler:
    def __init__(self, map_data, drones, paths):
        ...

    def initialize_simulation(self):
        ...

    def choose_path(self, drone):
        ...

    def can_move(self, drone, next_zone):
        ...

    def move_drone(self, drone):
        ...

    def process_turn(self):
        ...

    def simulation_finished(self):
        ...

    def run(self):
        ...